class ModelPriceData {
  String nomor,
      tanggal,
      namaPT,
      npwp,
      picUser,
      picPosition,
      contact,
      email,
      billingPic,
      billingAddress,
      billingContact,
      billingEmail,
      totalEmployee,
      diskonEmployee,
      ket1,
      hargaTraining,
      diskonTraining,
      ket2,
      hargaImplementasi,
      diskonImplementasi,
      ket3,
      hargaModifikasi,
      diskonModifikasi,
      ket4,
      emailSales;
}